## catch 내부에서 예외 발생 위험이 있는 코드 호출

catch 블록 내부에서 예외 발생 위험이 있는 코드를 호출하는 것은 일반적으로 권장되지 않는다. 그 이유는 추가로 예외가 발생하여 해당 catch 블록 이후의 코드가 실행되지 않을 수 있기 때문이다.

**그렇다면 재귀로 예외 발생이 안될 때까지 돌리면 되지 않을까?**

재귀로 예외 발생이 안될 때까지 돌리는 것도 일반적으로 권장되지 않는다. 재귀 호출이 계속해서 일어나면 스택 오버플로우와 같은 문제가 발생할 수 있기 때문이다.

catch 블록에서 예외 발생 가능성이 있는 코드를 호출하는 것은 무한 루프나 재귀적 호출과 같이 예외가 발생하면 프로그램이 제대로 종료되지 않을 수 있다. 예외 발생에 대한 예외 처리를 수행하는 블록에서 예외를
발생시키는 코드를 호출하면, 프로그램이 예외 발생 시점부터 무한 반복하거나 다른 예기치 않은 동작을 수행할 수 있다. 이러한 이유로, catch 블록에서는 가능한 한 예외가 발생하지 않도록 주의해서 코드를 작성하는
것이 좋다.
